services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_TOKEN: ${BOT_TOKEN}
    env_file:
      - path: .env
        required: true
    volumes:
      - ./docs:/app/documents:ro
      - ./sched:/app/schedule:ro
